# Generated by Django 3.1.4 on 2021-01-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_link', models.CharField(max_length=100)),
                ('insta_link', models.CharField(max_length=100)),
                ('twitter_link', models.CharField(max_length=100)),
                ('youtube_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
            ],
        ),
    ]
