# Generated by Django 3.1.4 on 2021-01-03 10:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_sitefooter_siteheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs_section_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
