# Generated by Django 3.1.4 on 2020-12-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20201210_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='subs_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
