# Generated by Django 3.1.4 on 2021-01-03 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0002_auto_20210103_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretubers',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 14, 46, 10, 733367)),
        ),
    ]
